export const GET_REQUESTS = 'GET_REQUESTS';
export const GET_LASTRISNO = 'GET_LASTRISNO';
export const ADD_REQUEST = 'ADD_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const REQUEST_ADDING = 'REQUEST_ADDING';
export const REQUESTS_LOADING = 'REQUESTS_LOADING';
export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUESTBYNO_LOADING = 'REQUESTBYNO_LOADING';